Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos9s"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "512"
  end

  config.vm.synced_folder "./scripts/", "/home/vagrant/scripts/", type: "virtualbox"

  config.vm.define "losylvesS" do |server|
    server.vm.network :private_network, ip: "192.168.56.110"
    server.vm.hostname = "losylvesS"
    server.vm.provider "virtualbox" do |vb|
        vb.name = "losylvesS"
    end
    server.vm.provision "shell", path: "./scripts/server.sh"
  end

  config.vm.define "losylvesSW" do |worker|
    worker.vm.network :private_network, ip: "192.168.56.111"
    worker.vm.hostname = "losylvesSW"
    worker.vm.provider "virtualbox" do |vb|
        vb.name = "losylvesSW"
    end
    worker.vm.provision "shell", path: "./scripts/worker.sh"
  end
end
