Vagrant.configure("2") do |config|
  # Use Libvirt-compatible box
  config.vm.box = "ol8"

  # Libvirt global configuration (optional)
  config.vm.provider "libvirt" do |lv|
    lv.memory = 512
    lv.cpus = 1
  end

  # Define VMs
  config.vm.define "losylvesS" do |server|
    server.vm.network :private_network, ip: "192.168.56.110"
    server.vm.hostname = "losylvesS"
    server.vm.provider "libvirt" do |lv|
    end
  end

  config.vm.define "losylvesSW" do |worker|
    worker.vm.network :private_network, ip: "192.168.56.111"
    worker.vm.hostname = "losylvesSW"
    worker.vm.provider "libvirt" do |lv|
    end
  end
end